version: '2'
services:
    trmntr-app:
        image: trmntr
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://trmntr-mariadb:3306/trmntr
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trmntr-mariadb:
        extends:
            file: mariadb.yml
            service: trmntr-mariadb
